import Head from 'next/head'
import Profile from '../components/Profile'
import RoomList from '../components/RoomList'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Welcome to Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-[#06283D] min-h-[100vh] flex md:flex-row flex-col items-center justify-center py-8'>
        <div className='min-h-[80vh] w-[80vw] bg-white rounded-md'>
          <Profile />
          <RoomList />
        </div>
      </div>
    </div>
  )
}
